language: objective-c
osx_image: xcode9.4
xcode_workspace: veryfirstpractice.xcworkspace

before_install:
   - gem install cocoapods
   - pod install

script: 
   - xcodebuild test -workspace veryfirstpractice.xcworkspace -scheme "veryfirstpractice" -destination 'platform=iOS Simulator,name=iPhone 8,OS=latest'
