language: objective-c
osx_image: xcode9.3

before_install:
   - gem install cocoapods
   - pod install

script: 
   - xcodebuild clean build -sdk iphonesimulator -workspace veryfirstpractice.xcworkspace -scheme veryfirstpractice CODE_SIGNING_REQUIRED=NO
   - xcodebuild test -workspace veryfirstpractice.xcworkspace -scheme "veryfirstpractice" -destination 'platform=iOS Simulator,name=iPhone 8,OS=11.4' CODE_SIGNING_REQUIRED=NO
