language: objective-c
osx_image: xcode9.3

before_install:
   - rvm use system
   - sudo gem install cocoapods -v '1.5.3'  

script: 
    - xcodebuild clean build -sdk iphonesimulator -workspace veryfirstpractice.xcworkspace -scheme veryfirstpractice CODE_SIGNING_REQUIRED=NO
