language: objective-c
osx_image: xcode9.3

before_install:
   - gem install cocoapods
   - pod install

script: 
    - xcodebuild clean build -sdk iphonesimulator -workspace veryfirstpractice.xcworkspace -scheme veryfirstpracticeTests CODE_SIGNING_REQUIRED=NO
