language: objective-c
xcode_workspace: veryfirstpractice.xcworkspace # path to your xcodeproj folder
xcode_scheme: veryfirstpracticeTests
osx_image: xcode9

before_install:
- rvm use system
- sudo gem install cocoapods

script:
xctool -workspace veryfirstpractice.xcworkspace -scheme veryfirstpractice build -sdk iphonesimulator

# hi guys
