language: objective-c
osx_image: xcode9.3

before_install:
   - gem install cocoapods
   - pod install
   - brew update
   - brew outdated xctool || brew upgrade xctool

script: 
   - xctool -workspace veryfirstpractice.xcworkspace -scheme veryfirstpractice -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
   - xctool test -workspace veryfirstpractice.xcworkspace -scheme veryfirstpracticeTests -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
