language: objective-c

before_install:
   - rvm use system
   - sudo gem install cocoapods -v '1.5.3'  

script: 
    xctool -workspace veryfirstpractice.xcworkspace -scheme veryfirstpractice build -sdk iphonesimulator
