language: objective-c
osx_image: xcode9.3

before_install:
  - git submodule update --init --recursive
  - brew update || brew update
  - brew outdated xctool || brew upgrade xctool

script:
  - rake test:ios
  - rake test:osx
  - rake test:xctool:ios
