language: objective-c
xcode_workspace: veryfirstpractice.xcworkspace # path to your xcodeproj folder
xcode_scheme: veryfirstpracticeTests
osx_image: xcode9

before_install:
- rvm use system
- sudo gem install cocoapods

script:
- xcodebuild test -project veryfirstpractice.xcodeproj -scheme veryfirstpractice -destination "platform=iOS Simulator,name=iPhone 7" -sdk iphonesimulator11.0 CODE_SIGNING_REQUIRED=NO
